import { DataActor, DataClass, DataSkill, DataItem, DataWeapon, DataArmor, DataEnemy, DataTroop, DataState, DataAnimation, DataTileset, DataCommonEvent, DataSystem, DataMapInfo, DataMap, DataCommand } from "./data";
import { Game_Temp, Game_System, Game_Screen, Game_Timer, Game_Message, Game_Switches, Game_Variables, Game_SelfSwitches, Game_Actors, Game_Party, Game_Troop, Game_Map, Game_Player } from "./objects";
export declare let $dataActors: DataActor[];
export declare let $dataClasses: DataClass[];
export declare let $dataSkills: DataSkill[];
export declare let $dataItems: DataItem[];
export declare let $dataWeapons: DataWeapon[];
export declare let $dataArmors: DataArmor[];
export declare let $dataEnemies: DataEnemy[];
export declare let $dataTroops: DataTroop[];
export declare let $dataStates: DataState[];
export declare let $dataAnimations: DataAnimation[];
export declare let $dataTilesets: DataTileset[];
export declare let $dataCommonEvents: DataCommonEvent[];
export declare let $dataSystem: DataSystem;
export declare let $dataMapInfos: DataMapInfo[];
export declare let $dataMap: DataMap;
export declare let $gameTemp: Game_Temp;
export declare let $gameSystem: Game_System;
export declare let $gameScreen: Game_Screen;
export declare let $gameTimer: Game_Timer;
export declare let $gameMessage: Game_Message;
export declare let $gameSwitches: Game_Switches;
export declare let $gameVariables: Game_Variables;
export declare let $gameSelfSwitches: Game_SelfSwitches;
export declare let $gameActors: Game_Actors;
export declare let $gameParty: Game_Party;
export declare let $gameTroop: Game_Troop;
export declare let $gameMap: Game_Map;
export declare let $gamePlayer: Game_Player;
export declare let $testEvent: DataCommand[] | null;
